
name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: selenium/standalone-chrome
    env:
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
    
    steps:
    - run: pwd
    - run: echo $SCREEN_WIDTH
    - run: echo $GITHUB_ACTOR
